get started guide
threefoldtecharchive/tfgrid_dashboard pull request #199
Opened 2022-08-23 07:50 UTC by xmonader

2022-08-23 14:26 UTC, rawdaGastan requested changes

2022-08-23 14:26 UTC, rawdaGastan commented on docs/Get_Started_Guide.md
> +- run the project : `yarn run`
can you change `yarn run` to `yarn serve`

2022-08-23 14:26 UTC, rawdaGastan commented on docs/Get_Started_Guide.md
> +- open your browser and navigate to http://localhost:3000/
the port is 8080 ?

2022-08-23 14:26 UTC, rawdaGastan commented on docs/Get_Started_Guide.md
> +    component: <Component.>,
remove extra . in <Component.> :D

2022-08-23 14:26 UTC, rawdaGastan commented on docs/Get_Started_Guide.md
> +- example :
you can mention that it's explorer example

2022-09-04 12:04 UTC, MohamedElmdary approved these changes

2022-09-04 13:01 UTC, rawdaGastan approved these changes

2022-09-04 14:10 UTC, merged