Add loader for Dao
threefoldtecharchive/tfgrid_dashboard pull request #206
Opened 2022-08-25 12:49 UTC by MohamedElmdary

2022-08-25 13:07 UTC, amiraabouhadid requested changes

2022-08-25 13:07 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> +                this.loadingProposals = true;
I don't see why you'd include this here as the loading proposals isn't displayed when you are voting

2022-08-25 13:07 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> +                });
I don't see why you'd include this here as the loading proposals isn't displayed when you are voting

2022-08-30 09:20 UTC, AhmedHanafy725 approved these changes

2022-08-30 09:24 UTC, amiraabouhadid approved these changes

2022-08-30 09:29 UTC, merged