fix ip generate and new balance
threefoldtecharchive/tfgrid_dashboard pull request #450
Opened 2022-12-28 16:47 UTC by A-Harby

### Description

Fix failed tests from the workflow.

### Changes

- Update new twin TFT balance.
- Add new method to randomly pick a public IPV4.
- Update IPV6 with a correct public IPV6. 

### Checklist

- [ ] Tests included
- [ ] Build pass
- [ ] Documentation
- [ ] Code format and docstrings

2023-03-08 15:23 UTC, mohamedamer453 requested changes
Other than the 2 comments that i mentioned, everything looks good and i tried all of the tests and everything worked without any issues :+1:

2023-03-08 15:23 UTC, mohamedamer453 commented on tests/frontend_selenium/tests/test_farm.py
>      Test Case: TC1141 - Enter valid IP
The test case was remove but its title is still available and it replaced the title of the next case.

same issue is present in other functions in the same file.

2023-03-08 15:23 UTC, mohamedamer453 commented on tests/frontend_selenium/tests/test_twin.py
> +def test_create_twin_relay(browser):
2 Tests in the test_twin file failed as seen below.

![image](https://user-images.githubusercontent.com/101194226/223752117-b13798f2-953a-436b-a792-a37064712157.png)

full logs can be found [here](https://gist.github.com/mohamedamer453/d319fbccf48605359283d57b0e56e6f8).

2023-03-09 10:23 UTC, mohamedamer453 requested changes
The mentioned issues in the last review were fixed. However new issues appeared in  `test_farm`,  other than that everything else is running smoothly and tested multiple times without any issues.

2023-03-09 10:23 UTC, mohamedamer453 commented on tests/frontend_selenium/tests/test_twin.py
> +def test_create_twin_relay(browser):
The issue was resolved and the `edit_twin_relay` test doesn't fail anymore

2023-03-09 10:23 UTC, mohamedamer453 commented on tests/frontend_selenium/tests/test_farm.py
> +def test_ip(browser):
All ip related tests in the test_farm file are failing.

![image](https://user-images.githubusercontent.com/101194226/223993560-00d1368b-ed51-485d-9958-3ce5ae8ddb3e.png)

Full logs can be found [here](https://gist.github.com/mohamedamer453/10ea68cb1ecd6285bd73ec8d1d458e45).

2023-03-09 13:01 UTC, A-Harby commented on tests/frontend_selenium/tests/test_farm.py
> +def test_ip(browser):
It's an issue in the farm page, adding IP to the farm.
And its reported and once its fixed the tests should pass.
https://github.com/threefoldtech/tfgrid_dashboard/issues/552

2023-03-09 13:07 UTC, mohamedamer453 approved these changes
The issues related to the `test_farm` page wasn't related to the tests #552

2023-03-09 13:25 UTC, merged