Fixing node up-time
threefoldtecharchive/tfgrid_dashboard pull request #551
Opened 2023-03-08 19:05 UTC by sameh-farouk

### Description

Fixing node's availability calculations. 
should now calculate the uptime over the current minting period.

The Calculations are based on my understanding of @LeeSmet comment [here] (https://github.com/threefoldtech/tfgrid_dashboard/issues/366#issuecomment-1304436906)
 

### Changes

- Function `getNodeDowntime` is renamed to `getNodeAvailability` and now returns both downtime and the time elapsed since the current minting period started.
- Downtime is now calculated over the current minting period.
- The node interface has been changed to include an `availability` attribute with a new `NodeAvailability` interface instead of downtime.
- Uptime percentage is now calculated based on calculated `node.availability`  `((uptime over the current minting period / current minting period) * 100)`, instead of `node.uptime` (which is the uptime since the node's last reboot).

### Related Issues

https://github.com/threefoldtech/tfgrid_dashboard/issues/466

### Checklist

- [ ] Tests included
- [X] Build pass
- [ ] Documentation
- [X] Code format and docstrings

2023-03-09 15:37 UTC, LeeSmet requested changes
Looks good, just one small remark :)

2023-03-09 15:37 UTC, LeeSmet commented on src/portal/lib/nodes.ts
> +  if (elapsedSinceLastUptimeEvent >= 60) {
since this is expressed in seconds and uptime events are supposed to happen every 40 minutes, I'd change this into `> 3600` (one hour)

2023-03-10 09:01 UTC, sameh-farouk commented on src/portal/lib/nodes.ts
> +  if (elapsedSinceLastUptimeEvent >= 60) {
good catch! fixed now.

2023-03-16 09:09 UTC, amiraabouhadid requested changes
please remove all unused variables shown by the warnings in github actions build

2023-03-19 08:43 UTC, amiraabouhadid approved these changes

2023-03-19 08:46 UTC, merged