modifiy spaces and icons
threefoldtecharchive/tfgrid_dashboard pull request #56
Opened 2022-06-19 10:56 UTC by samaradel

Add spaces between parents and children.

![image](https://user-images.githubusercontent.com/11662805/174477498-f245d190-955c-491b-85b0-7df47e1a47da.png)

Related issues:

[#55](https://github.com/threefoldtech/tfgrid_dashboard/issues/55)

2022-06-27 14:28 UTC, MohamedElmdary approved these changes

2022-06-28 11:54 UTC, amiraabouhadid requested changes
Hey @samaradel , please do not remove the logic used to calculate the progress bar width/color and the Yes/No buttons width. It needs to look like this: 

![Screenshot from 2022-06-28 13-49-51](https://user-images.githubusercontent.com/56790126/176172295-398046d2-32e7-4a2d-85bd-cb1154cd7ec9.png)
![Screenshot from 2022-06-28 13-52-07](https://user-images.githubusercontent.com/56790126/176172312-9f5a9804-5f06-482e-8e59-e74a44f4d3f9.png)

2022-06-28 11:54 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> +            width="100px"
hey, @samaradel please do not remove the width related to the number of ayes and nays on a proposal as it should display as the proposal's nays and ayes are trying to reach the threshold.

2022-06-28 11:54 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> +                marginRight: 'auto',
Hey @samaradel , please make the progress bar green for ayes and red for nays so there is a clearer visualization of which is winning the vote

2022-06-28 11:54 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> -              :sm="Math.round(proposal.ayesProgress*12/100)===12? 11: proposal.ayesProgress*12/100"
Please also do not remove this as it is used to calculate and visualize the progress based on vote weights

2022-06-28 11:54 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> -              :sm="Math.round(proposal.nayesProgress*12/100)===12? 11: proposal.nayesProgress*12/100"
please leave the calculation here as well to allow visualization of nayes progress as such
![Screenshot from 2022-06-28 13-49-51](https://user-images.githubusercontent.com/56790126/176171722-cc947e8a-110f-48ae-9249-d326993f19b6.png)

2022-06-28 11:58 UTC, amiraabouhadid commented
@samaradel Please also link all the issues you have addressed to this pull request so that they are automatically closed.
Thanks,
Amira

2022-07-03 09:59 UTC, samaradel commented
@amiraabouhadid all resolved now

2022-07-03 14:04 UTC, amiraabouhadid requested changes

2022-07-03 14:04 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> -            :width="`${proposal.nayes.length *100 + 100}`"
@ehab-hassan @samaradel please include this

2022-07-03 14:04 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> -            :width="`${proposal.ayes.length *100 + 100}`"
@samaradel @ehab-hassan please include this

2022-07-03 14:06 UTC, amiraabouhadid commented on src/portal/views/Dao.vue
> -            :width="`${proposal.ayes.length *100 + 100}`"
fixed it, thanks

2022-07-03 14:17 UTC, amiraabouhadid approved these changes

2022-07-03 14:17 UTC, merged